# Test profile configuration
spring:
  config:
    activate:
      on-profile: uat3
  security:
    user:
      name: uat3
      password: uat3Password
  datasource:
    url: jdbc:mysql://localhost:3306/library_db
    driverClassName: com.mysql.cj.jdbc.Driver
    username: root
    password: pass
    # Optionally configure connection pooling (HikariCP is default in Spring Boot)
    hikari:
      maximum-pool-size: 10  # Maximum number of connections in the pool
      minimum-idle: 5        # Minimum number of idle connections
      pool-name: HikariCP     # Optional name for your connection pool
  sql:
    init:
      mode: never
  jpa:
    #database-platform: org.hibernate.dialect.MySQLDialect  # Make sure to use MySQLDialect

    # Make sure to use MySQLDialect
    show-sql: true   # Set to true to log SQL queries in the console (for debugging)
    hibernate:
      dialect: org.hibernate.dialect.MySQLDialect
      ddl-auto: update    # Can be 'none', 'update', 'create', 'create-drop', etc.
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
  logging:
    level:
      root: INFO
      org.springframework: DEBUG
      org.hibernate: WARN
      com.example: DEBUG

