# Test profile configuration
spring:
  config:
    activate:
      on-profile: dev
  security:
    user:
      name: dev
      password: devPassword
  datasource:
    url: jdbc:mysql://localhost:3306/library_db
    driverClassName: com.mysql.cj.jdbc.Driver
    username: root
    password: pass
    # Optionally configure connection pooling (HikariCP is default in Spring Boot)
    hikari:
      maximum-pool-size: 10  # Maximum number of connections in the pool
      minimum-idle: 5        # Minimum number of idle connections
      pool-name: HikariCP     # Optional name for your connection pool
  sql:
    init:
      mode: never
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect  # Make sure to use MySQLDialect
    show-sql: true   # Set to true to log SQL queries in the console (for debugging)
    hibernate:
      ddl-auto: update    # Can be 'none', 'update', 'create', 'create-drop', etc.
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
  logging:
    level:
      root: INFO
      org.springframework: INFO
      org.hibernate: WARN
      com.example: DEBUG
    pattern:
      console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"

    file:
      name: "logs/springboot-app.log"
      max-size: 10MB
      max-history: 30