# Test profile configuration
spring:
  config:
    activate:
      on-profile: ${SPRING_PROFILES_ACTIVE}
  security:
    user:
      name: prod
      password: prodPassword
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    driverClassName: ${SPRING_DATASOURCE_DRIVER}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    # Optionally configure connection pooling (HikariCP is default in Spring Boot)
    hikari:
      maximum-pool-size: ${HIKARI_MAX_POOL_SIZE}  # Maximum number of connections in the pool
      minimum-idle: ${HIKARI_MIN_IDLE_CONN}        # Minimum number of idle connections
      pool-name: HikariCP     # Optional name for your connection pool
  sql:
    init:
      #schema-location: classpath:/sql/schema.sql
      #data-location: classpath:sql/data.sql
      mode: never
  jpa:
    #database-platform: org.hibernate.dialect.MySQLDialect  # Make sure to use MySQLDialect    show-sql: false
    hibernate:
      dialect: ${SPRING_DATASOURCE_DIALECT}
      ddl-auto: update
    properties:
      hibernate:
        format_sql: ${SQL_FLAG}
        use_sql_comments: ${SQL_FLAG}
  logging:
    level:
      root: ${LOG_LEVEL}
      org.springframework: ${LOG_LEVEL}
