drop table CUSTOMER_T if exists;
create table CUSTOMER_T (
    ID INTEGER AUTO_INCREMENT PRIMARY KEY,
    VERSION INTEGER,
	FIRST_NAME varchar(255),
	MIDDLE_NAME varchar(255),
	LAST_NAME varchar(255),
	EMAIL_ADDRESS varchar(255) not null,
	COUNTRY_CODE varchar(15),
	AREA_CODE INTEGER,
	PREFIX INTEGER,
	LINE_NUMBER INTEGER,
	unique(EMAIL_ADDRESS)
);

