apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-boot-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spring-boot-app
  template:
    metadata:
      labels:
        app: spring-boot-app
    spec:
      containers:
      - name: spring-boot-container
        image: sunilthedevops/my-springboot-curd-app:latest   # Replace with your Docker Hub image name and tag
        env:
          - name: SPRING_DATASOURCE_URL
            valueFrom:
              configMapKeyRef:
                name: app-config
                key: SPRING_DATASOURCE_URL
          - name: SPRING_DATASOURCE_USERNAME
            valueFrom:
              secretKeyRef:
                name: db-secret
                key: DB_USERNAME
          - name: SPRING_DATASOURCE_PASSWORD
            valueFrom:
              secretKeyRef:
                name: db-secret
                key: DB_PASSWORD
          - name: SPRING_PROFILES_ACTIVE
            valueFrom:
              configMapKeyRef:
                name: app-config
                key: SPRING_PROFILES_ACTIVE
          - name: SPRING_DATASOURCE_DRIVER
            valueFrom:
              configMapKeyRef:
                name: app-config
                key: SPRING_DATASOURCE_DRIVER
          - name: HIKARI_MAX_POOL_SIZE
            valueFrom:
              configMapKeyRef:
                name: app-config
                key: HIKARI_MAX_POOL_SIZE
          - name: HIKARI_MIN_IDLE_CONN
            valueFrom:
              configMapKeyRef:
                name: app-config
                key: HIKARI_MIN_IDLE_CONN
          - name: SPRING_DATASOURCE_DIALECT
            valueFrom:
              configMapKeyRef:
                name: app-config
                key: SPRING_DATASOURCE_DIALECT
          - name: SQL_FLAG
            valueFrom:
              configMapKeyRef:
                name: app-config
                key: SQL_FLAG
          - name: LOG_LEVEL
            valueFrom:
              configMapKeyRef:
                name: app-config
                key: LOG_LEVEL
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "500m"
            memory: "512Mi"